import type { ExerciseDefinition, MuscleGroup } from "./types";

// Full exercise catalog covering Mass Impact, RAVAGE, and Hers programs.
// Secondary muscle factors follow RP conventions:
//   - Rows/pulldowns → biceps 0.5
//   - Any pressing movement → triceps 0.5, front_delts 0.5
//   - Squat / leg press / lunge patterns → glutes 0.5
//   - RDL / back extension patterns → glutes 0.5
//   - Hip thrust → hamstrings 0.5
//   - Farmer's walk → forearms 0.5
export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  // ─────────────────────────────────────────────
  // BACK
  // ─────────────────────────────────────────────
  {
    id: "yates-row",
    name: "Yates Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "barbell",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "seated-wide-grip-row-cable",
    name: "Seated Wide-Grip Row (Cable)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "single-arm-row-cable",
    name: "Single Arm Row (Cable)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "pull-up-bodyweight",
    name: "Pull-Up (Bodyweight)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "pull-up-neutral-grip-bodyweight",
    name: "Pull-Up (Neutral Grip, Bodyweight)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "bodyweight",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "standing-pullover-cable",
    name: "Standing Pullover (Cable)",
    primaryMuscle: "back",
    type: "stretch",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "bent-over-row-barbell",
    name: "Bent Over Row (Barbell)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "single-arm-row-dumbbell",
    name: "Single Arm Row (Dumbbell)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "narrow-neutral-pulldown",
    name: "Narrow Neutral Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "wide-overhand-pulldown",
    name: "Wide Overhand Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "1-arm-machine-row",
    name: "1 Arm Machine Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "machine",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "seated-row-cable",
    name: "Seated Row (Cable)",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "helms-row",
    name: "Helms Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "dumbbell",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "wide-neutral-pulldown",
    name: "Wide Neutral Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "single-arm-cable-row",
    name: "Single Arm Cable Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  // Cable pullover is the same movement as Standing Pullover (Cable) under a different name —
  // kept as a separate entry so program data using either name resolves correctly.
  {
    id: "cable-pullover",
    name: "Cable Pullover",
    primaryMuscle: "back",
    type: "stretch",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "half-kneeling-one-arm-lat-pulldown",
    name: "Half Kneeling One-Arm Lat Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "meadows-row",
    name: "Meadows Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "barbell",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "cross-body-lat-pulldown",
    name: "Cross Body Lat Pulldown",
    primaryMuscle: "back",
    type: "compound",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "straight-arm-cable-pulldown",
    name: "Straight-Arm Cable Pulldown",
    primaryMuscle: "back",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "dumbbell-lat-pullover",
    name: "Dumbbell Lat Pullover",
    primaryMuscle: "back",
    type: "stretch",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "deficit-pendlay-row",
    name: "Deficit Pendlay Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },
  {
    id: "croc-row",
    name: "Croc Row",
    primaryMuscle: "back",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "biceps", factor: 0.5 }],
  },

  // ─────────────────────────────────────────────
  // CHEST
  // ─────────────────────────────────────────────
  {
    id: "pec-deck-machine",
    name: "Pec Deck (Machine)",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "incline-bench-press-barbell",
    name: "Incline Bench Press (Barbell)",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "cable-chest-fly",
    name: "Cable Chest Fly",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "dip-weighted",
    name: "Dip (Weighted)",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "ad-press",
    name: "AD Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "machine",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "incline-bench-press-dumbbell",
    name: "Incline Bench Press (Dumbbell)",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "close-grip-larsen-press",
    name: "Close Grip Larsen Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "barbell",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "smith-reverse-grip-bench",
    name: "Smith Reverse Grip Bench",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "smith_machine",
    secondaryMuscles: [{ muscle: "triceps", factor: 0.5 }],
  },
  {
    id: "bench-press-barbell",
    name: "Bench Press (Barbell)",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "chest-press-machine",
    name: "Chest Press (Machine)",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "incline-db-fly",
    name: "Incline DB Fly",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "dumbbell",
    secondaryMuscles: [],
  },
  {
    id: "seated-cable-pec-fly",
    name: "Seated Cable Pec Fly",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "flat-dumbbell-press",
    name: "Flat Dumbbell Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "deficit-push-up",
    name: "Deficit Push-Up",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "guillotine-press",
    name: "Guillotine Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "smith-machine-bench-press",
    name: "Smith Machine Bench Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "smith_machine",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "incline-smith-machine-press",
    name: "Incline Smith Machine Press",
    primaryMuscle: "chest",
    type: "compound",
    equipment: "smith_machine",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "cable-press-around",
    name: "Cable Press-Around",
    primaryMuscle: "chest",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // SIDE DELTS
  // ─────────────────────────────────────────────
  {
    id: "arnold-press",
    name: "Arnold Press",
    primaryMuscle: "side_delts",
    type: "compound",
    equipment: "dumbbell",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "lateral-raise-dumbbell",
    name: "Lateral Raise (Dumbbell)",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "lu-raise",
    name: "Lu Raise",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "dumbbell",
    secondaryMuscles: [],
  },
  {
    id: "partial-lateral-raise-cable",
    name: "Partial Lateral Raise (Cable)",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "cable",
    secondaryMuscles: [],
  },
  {
    id: "lateral-raise-cable",
    name: "Lateral Raise (Cable)",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "seated-shoulder-press-dumbbell",
    name: "Seated Shoulder Press (Dumbbell)",
    primaryMuscle: "side_delts",
    type: "compound",
    equipment: "dumbbell",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },
  {
    id: "lateral-raise-machine",
    name: "Lateral Raise (Machine)",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "cable-y-raise",
    name: "Cable Y Raise",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "behind-the-back-cable-lateral-raise",
    name: "Behind-the-Back Cable Lateral Raise",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "cable-upright-row",
    name: "Cable Upright Row",
    primaryMuscle: "side_delts",
    type: "compound",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [{ muscle: "traps", factor: 0.5 }],
  },
  {
    id: "standing-machine-lateral-raise",
    name: "Standing Machine Lateral Raise",
    primaryMuscle: "side_delts",
    type: "isolation",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // REAR DELTS
  // ─────────────────────────────────────────────
  {
    id: "skiers",
    name: "Skiers",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "cable",
    secondaryMuscles: [{ muscle: "traps", factor: 0.5 }],
  },
  {
    id: "rear-delt-fly-cable",
    name: "Rear Delt Fly (Cable)",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    // Traps assist on the retraction portion
    secondaryMuscles: [{ muscle: "traps", factor: 0.5 }],
  },
  {
    id: "reverse-pec-dec",
    name: "Reverse Pec Dec",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "reverse-cable-fly",
    name: "Reverse Cable Fly",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "chest-supported-rear-delt-fly",
    name: "Chest-Supported Rear Delt Fly",
    primaryMuscle: "rear_delts",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // FRONT DELTS
  // ─────────────────────────────────────────────
  {
    id: "klokov-press",
    name: "Klokov Press",
    primaryMuscle: "front_delts",
    type: "compound",
    equipment: "barbell",
    // Behind-the-neck press; upper traps and side delts assist
    secondaryMuscles: [
      { muscle: "side_delts", factor: 0.5 },
      { muscle: "triceps", factor: 0.5 },
    ],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    primaryMuscle: "front_delts",
    type: "compound",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "side_delts", factor: 0.5 },
    ],
  },
  {
    id: "seated-dumbbell-overhead-press",
    name: "Seated Dumbbell Overhead Press",
    primaryMuscle: "front_delts",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "triceps", factor: 0.5 },
      { muscle: "side_delts", factor: 0.5 },
    ],
  },

  // ─────────────────────────────────────────────
  // TRAPS
  // ─────────────────────────────────────────────
  {
    id: "power-shrug",
    name: "Power Shrug",
    primaryMuscle: "traps",
    type: "compound",
    equipment: "barbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "farmers-walk-weighted",
    name: "Farmer's Walk (Weighted)",
    primaryMuscle: "traps",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    // Forearms under high isometric load during carry
    secondaryMuscles: [{ muscle: "forearms", factor: 0.5 }],
  },
  {
    id: "upright-row-barbell",
    name: "Upright Row (Barbell)",
    primaryMuscle: "traps",
    type: "compound",
    equipment: "barbell",
    // Upper trap / side delt overlap
    secondaryMuscles: [{ muscle: "side_delts", factor: 0.5 }],
  },
  {
    id: "overhead-shrug",
    name: "Overhead Shrug",
    primaryMuscle: "traps",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // QUADS
  // ─────────────────────────────────────────────
  {
    id: "squat-barbell",
    name: "Squat (Barbell)",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "barbell",
    tier: "S",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "walking-lunge-dumbbell",
    name: "Walking Lunge (Dumbbell)",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "smith-machine-hack-squat",
    name: "Smith Machine Hack Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "smith_machine",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "bodyweight",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    type: "isolation",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "dumbbell",
    tier: "S",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "step-up-high-box",
    name: "Step-Up (High Box)",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "dumbbell",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "front-squat-barbell",
    name: "Front Squat (Barbell)",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "platz-squat",
    name: "Platz Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "barbell",
    // Narrow stance, heels elevated — extreme quad bias, minimal glute contribution
    secondaryMuscles: [],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "pendulum-squat",
    name: "Pendulum Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "smith-machine-squat",
    name: "Smith Machine Squat",
    primaryMuscle: "quads",
    type: "compound",
    equipment: "smith_machine",
    tier: "S",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "sissy-squat",
    name: "Sissy Squat",
    primaryMuscle: "quads",
    type: "isolation",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "reverse-nordic-curl",
    name: "Reverse Nordic Curl",
    primaryMuscle: "quads",
    type: "isolation",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // HAMSTRINGS
  // ─────────────────────────────────────────────
  {
    id: "romanian-deadlift-barbell",
    name: "Romanian Deadlift (Barbell)",
    primaryMuscle: "hamstrings",
    type: "compound",
    equipment: "barbell",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "back-extension-weighted",
    name: "Back Extension (Weighted)",
    primaryMuscle: "hamstrings",
    type: "compound",
    equipment: "bodyweight",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "seated-hamstring-curl",
    name: "Seated Hamstring Curl",
    primaryMuscle: "hamstrings",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    primaryMuscle: "hamstrings",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "nordic-curl",
    name: "Nordic Curl",
    primaryMuscle: "hamstrings",
    type: "compound",
    equipment: "bodyweight",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    primaryMuscle: "hamstrings",
    type: "compound",
    equipment: "barbell",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },
  {
    id: "single-leg-db-stiff-leg-deadlift",
    name: "Single-Leg DB Stiff-Leg Deadlift",
    primaryMuscle: "hamstrings",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "glutes", factor: 0.5 }],
  },

  // ─────────────────────────────────────────────
  // GLUTES
  // ─────────────────────────────────────────────
  {
    id: "hip-thrust-barbell",
    name: "Hip Thrust (Barbell)",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "b-stance-hip-thrust",
    name: "B-Stance Hip Thrust",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "barbell",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "cable-kickback",
    name: "Cable Kickback",
    primaryMuscle: "glutes",
    type: "isolation",
    equipment: "cable",
    secondaryMuscles: [],
  },
  {
    id: "glute-focused-back-extension",
    name: "Glute-Focused Back Extension",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "bodyweight",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "machine-hip-abduction",
    name: "Machine Hip Abduction",
    primaryMuscle: "glutes",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    primaryMuscle: "glutes",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "elevated-front-foot-lunge",
    name: "Elevated Front-Foot Lunge",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "dumbbell",
    tier: "S",
    secondaryMuscles: [{ muscle: "quads", factor: 0.5 }],
  },
  {
    id: "45-degree-back-extension",
    name: "45-Degree Back Extension",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "bodyweight",
    tier: "S",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "single-leg-dumbbell-hip-thrust",
    name: "Single-Leg Dumbbell Hip Thrust",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [{ muscle: "hamstrings", factor: 0.5 }],
  },
  {
    id: "smith-machine-lunge",
    name: "Smith Machine Lunge",
    primaryMuscle: "glutes",
    type: "compound",
    equipment: "smith_machine",
    tier: "A",
    secondaryMuscles: [{ muscle: "quads", factor: 0.5 }],
  },

  // ─────────────────────────────────────────────
  // CALVES
  // ─────────────────────────────────────────────
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    primaryMuscle: "calves",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    primaryMuscle: "calves",
    type: "isolation",
    equipment: "machine",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // BICEPS
  // ─────────────────────────────────────────────
  {
    id: "spider-curl",
    name: "Spider Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "preacher-curl-barbell",
    name: "Preacher Curl (Barbell)",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "barbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "incline-curl-dumbbell",
    name: "Incline Curl (Dumbbell)",
    primaryMuscle: "biceps",
    type: "stretch",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "hammer-curl-cable",
    name: "Hammer Curl (Cable)",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "cable",
    secondaryMuscles: [],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "bicep-curl-barbell",
    name: "Bicep Curl (Barbell)",
    primaryMuscle: "biceps",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "preacher-curl-dumbbell",
    name: "Preacher Curl (Dumbbell)",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "dumbbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "machine",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "bayesian-cable-curl",
    name: "Bayesian Cable Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "creature-curl",
    name: "Creature Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "dumbbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "ez-bar-curl",
    name: "EZ Bar Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "lying-dumbbell-curl",
    name: "Lying Dumbbell Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "standard-cable-curl",
    name: "Standard Cable Curl",
    primaryMuscle: "biceps",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // TRICEPS
  // ─────────────────────────────────────────────
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    primaryMuscle: "triceps",
    type: "compound",
    equipment: "barbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "overhead-tricep-extension-cable",
    name: "Overhead Tricep Extension (Cable)",
    primaryMuscle: "triceps",
    type: "stretch",
    equipment: "cable",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    primaryMuscle: "triceps",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "standing-overhead-extension",
    name: "Standing Overhead Extension",
    primaryMuscle: "triceps",
    type: "stretch",
    equipment: "dumbbell",
    secondaryMuscles: [],
  },
  {
    id: "leaning-overhead-extension",
    name: "Leaning Overhead Extension",
    primaryMuscle: "triceps",
    type: "stretch",
    equipment: "cable",
    secondaryMuscles: [],
  },
  {
    id: "dumbbell-skull-crusher",
    name: "Dumbbell Skull Crusher",
    primaryMuscle: "triceps",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "katana-triceps-extension",
    name: "Katana Triceps Extension",
    primaryMuscle: "triceps",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "cable-tricep-kickback",
    name: "Cable Tricep Kickback",
    primaryMuscle: "triceps",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "smith-machine-jm-press",
    name: "Smith Machine JM Press",
    primaryMuscle: "triceps",
    type: "compound",
    equipment: "smith_machine",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    primaryMuscle: "triceps",
    type: "compound",
    equipment: "barbell",
    tier: "A",
    secondaryMuscles: [
      { muscle: "chest", factor: 0.5 },
      { muscle: "front_delts", factor: 0.5 },
    ],
  },

  // ─────────────────────────────────────────────
  // ABS
  // ─────────────────────────────────────────────
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    primaryMuscle: "abs",
    type: "isolation",
    equipment: "bodyweight",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    primaryMuscle: "abs",
    type: "isolation",
    equipment: "cable",
    secondaryMuscles: [],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    primaryMuscle: "abs",
    type: "isolation",
    equipment: "cable",
    tier: "A",
    secondaryMuscles: [],
  },
  {
    id: "cardio",
    name: "Cardio",
    primaryMuscle: "abs",
    type: "isolation",
    equipment: "bodyweight",
    secondaryMuscles: [],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    primaryMuscle: "abs",
    type: "compound",
    equipment: "bodyweight",
    tier: "S",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // NECK
  // ─────────────────────────────────────────────
  {
    id: "neck-curl",
    name: "Neck Curl",
    primaryMuscle: "neck",
    type: "isolation",
    equipment: "bodyweight",
    secondaryMuscles: [],
  },
  {
    id: "neck-flexion",
    name: "Neck Flexion",
    primaryMuscle: "neck",
    type: "isolation",
    equipment: "bodyweight",
    secondaryMuscles: [],
  },

  // ─────────────────────────────────────────────
  // FOREARMS
  // ─────────────────────────────────────────────
  {
    id: "wrist-flexion-extension",
    name: "Wrist Flexion/Extension",
    primaryMuscle: "forearms",
    type: "isolation",
    equipment: "dumbbell",
    secondaryMuscles: [],
  },
  {
    id: "wrist-curl",
    name: "Wrist Curl",
    primaryMuscle: "forearms",
    type: "isolation",
    equipment: "dumbbell",
    tier: "S",
    secondaryMuscles: [],
  },
  {
    id: "reverse-wrist-curl",
    name: "Reverse Wrist Curl",
    primaryMuscle: "forearms",
    type: "isolation",
    equipment: "dumbbell",
    tier: "A",
    secondaryMuscles: [],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Lookup helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Find an exercise by name.
 * 1. Exact match (case-insensitive)
 * 2. Prefix match — query is a prefix of the stored name (e.g. "Hip Thrust"
 *    matches "Hip Thrust (Barbell)")
 * Returns the first match found; undefined if nothing matches.
 */
export function findExercise(query: string): ExerciseDefinition | undefined {
  const q = query.toLowerCase().trim();

  // Pass 1: exact match
  const exact = EXERCISE_LIBRARY.find((e) => e.name.toLowerCase() === q);
  if (exact) return exact;

  // Pass 2: prefix match (query is a prefix of the stored name)
  const prefix = EXERCISE_LIBRARY.find((e) =>
    e.name.toLowerCase().startsWith(q)
  );
  return prefix;
}

/**
 * Return all exercises whose primary muscle matches the given group.
 */
export function getExercisesForMuscle(
  muscle: MuscleGroup
): ExerciseDefinition[] {
  return EXERCISE_LIBRARY.filter((e) => e.primaryMuscle === muscle);
}
