import type { RpTemplate } from "./rp-types";

export const RP_TEMPLATE_NF3: RpTemplate = {
  id: "rp-nf3",
  name: "RP Full Body 3-Day",
  daysPerWeek: 3,
  dayTitles: ["Push Emphasis", "Legs Emphasis", "Pull Emphasis"],
  restDayPattern: [1, 1, 1],
  slots: [
    {
      slotId: "d1-01",
      muscleCategory: "Horizontal Push",
      dayNumber: 1,
      order: 1,
      pairedSlotId: "d2-08",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d1-02",
      muscleCategory: "Chest Isolation or Triceps",
      dayNumber: 1,
      order: 2,
      pairedSlotId: "d2-08",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 0 },
    },
    {
      slotId: "d1-03",
      muscleCategory: "Incline Push or Front Delts",
      dayNumber: 1,
      order: 3,
      pairedSlotId: "d2-07",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d1-04",
      muscleCategory: "Side Delts",
      dayNumber: 1,
      order: 4,
      pairedSlotId: "d2-04",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-05",
      muscleCategory: "Vertical Pull",
      dayNumber: 1,
      order: 5,
      pairedSlotId: "d2-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-06",
      muscleCategory: "Horizontal Pull",
      dayNumber: 1,
      order: 6,
      pairedSlotId: "d2-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-07",
      muscleCategory: "Hamstrings Isolation",
      dayNumber: 1,
      order: 7,
      pairedSlotId: "d2-03",
      isAutoregulated: false,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d1-08",
      muscleCategory: "Quads",
      dayNumber: 1,
      order: 8,
      pairedSlotId: "d2-01",
      isAutoregulated: false,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d2-01",
      muscleCategory: "Quads",
      dayNumber: 2,
      order: 1,
      pairedSlotId: "d1-08",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d2-02",
      muscleCategory: "Quads",
      dayNumber: 2,
      order: 2,
      pairedSlotId: "d1-08",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 0 },
    },
    {
      slotId: "d2-03",
      muscleCategory: "Hamstrings Hip Hinge",
      dayNumber: 2,
      order: 3,
      pairedSlotId: "d3-08",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d2-04",
      muscleCategory: "Side Delts",
      dayNumber: 2,
      order: 4,
      pairedSlotId: "d3-03",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d2-05",
      muscleCategory: "Vertical Pull",
      dayNumber: 2,
      order: 5,
      pairedSlotId: "d3-01",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d2-06",
      muscleCategory: "Horizontal Pull",
      dayNumber: 2,
      order: 6,
      pairedSlotId: "d3-02",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d2-07",
      muscleCategory: "Incline Push or Front Delts",
      dayNumber: 2,
      order: 7,
      pairedSlotId: "d3-06",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d2-08",
      muscleCategory: "Horizontal Push",
      dayNumber: 2,
      order: 8,
      pairedSlotId: "d3-05",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d3-01",
      muscleCategory: "Vertical Pull",
      dayNumber: 3,
      order: 1,
      pairedSlotId: "d1-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d3-02",
      muscleCategory: "Horizontal Pull",
      dayNumber: 3,
      order: 2,
      pairedSlotId: "d1-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d3-03",
      muscleCategory: "Rear Delts or Side Delts",
      dayNumber: 3,
      order: 3,
      pairedSlotId: "d1-04",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d3-04",
      muscleCategory: "Biceps",
      dayNumber: 3,
      order: 4,
      pairedSlotId: "d1-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-05",
      muscleCategory: "Horizontal Push",
      dayNumber: 3,
      order: 5,
      pairedSlotId: "d1-01",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-06",
      muscleCategory: "Incline Push",
      dayNumber: 3,
      order: 6,
      pairedSlotId: "d1-01",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-07",
      muscleCategory: "Glutes",
      dayNumber: 3,
      order: 7,
      pairedSlotId: "d2-03",
      isAutoregulated: false,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d3-08",
      muscleCategory: "Hamstrings Isolation",
      dayNumber: 3,
      order: 8,
      pairedSlotId: "d1-07",
      isAutoregulated: false,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
  ],
  exerciseCategories: {},
};
