import type { RpTemplate } from "./rp-types";

export const RP_TEMPLATE_NF4: RpTemplate = {
  id: "rp-nf4",
  name: "RP Full Body 4-Day",
  daysPerWeek: 4,
  dayTitles: ["Upper Body", "Lower Body", "Upper Body", "Lower Body"],
  restDayPattern: [0, 1, 1, 1],
  slots: [
    {
      slotId: "d1-01",
      muscleCategory: "Incline Push",
      dayNumber: 1,
      order: 1,
      pairedSlotId: "d3-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d1-02",
      muscleCategory: "Chest Isolation or Triceps",
      dayNumber: 1,
      order: 2,
      pairedSlotId: "d3-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 0 },
    },
    {
      slotId: "d1-03",
      muscleCategory: "Horizontal Push",
      dayNumber: 1,
      order: 3,
      pairedSlotId: "d3-05",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 3, resensitization: 1 },
    },
    {
      slotId: "d1-04",
      muscleCategory: "Horizontal Pull",
      dayNumber: 1,
      order: 4,
      pairedSlotId: "d3-03",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-05",
      muscleCategory: "Vertical Pull",
      dayNumber: 1,
      order: 5,
      pairedSlotId: "d3-01",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-06",
      muscleCategory: "Side Delts",
      dayNumber: 1,
      order: 6,
      pairedSlotId: "d3-04",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d1-07",
      muscleCategory: "Abs",
      dayNumber: 1,
      order: 7,
      pairedSlotId: "d3-07",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d2-01",
      muscleCategory: "Quads",
      dayNumber: 2,
      order: 1,
      pairedSlotId: "d4-03",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d2-02",
      muscleCategory: "Quads",
      dayNumber: 2,
      order: 2,
      pairedSlotId: "d4-03",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 0 },
    },
    {
      slotId: "d2-03",
      muscleCategory: "Hamstring Isolation",
      dayNumber: 2,
      order: 3,
      pairedSlotId: "d4-02",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d2-04",
      muscleCategory: "Calves",
      dayNumber: 2,
      order: 4,
      pairedSlotId: "d4-06",
      isAutoregulated: false,
      baseSets: { basic: 6, metabolite: 6, resensitization: 5 },
    },
    {
      slotId: "d2-05",
      muscleCategory: "Triceps",
      dayNumber: 2,
      order: 5,
      pairedSlotId: "d3-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d2-06",
      muscleCategory: "Front Delts",
      dayNumber: 2,
      order: 6,
      pairedSlotId: "d3-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-01",
      muscleCategory: "Vertical Pull",
      dayNumber: 3,
      order: 1,
      pairedSlotId: "d1-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d3-02",
      muscleCategory: "Vertical Pull",
      dayNumber: 3,
      order: 2,
      pairedSlotId: "d1-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 0 },
    },
    {
      slotId: "d3-03",
      muscleCategory: "Horizontal Pull",
      dayNumber: 3,
      order: 3,
      pairedSlotId: "d1-04",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d3-04",
      muscleCategory: "Rear or Side Delts",
      dayNumber: 3,
      order: 4,
      pairedSlotId: "d1-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d3-05",
      muscleCategory: "Horizontal Push",
      dayNumber: 3,
      order: 5,
      pairedSlotId: "d1-03",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-06",
      muscleCategory: "Incline Push",
      dayNumber: 3,
      order: 6,
      pairedSlotId: "d1-01",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d3-07",
      muscleCategory: "Abs",
      dayNumber: 3,
      order: 7,
      pairedSlotId: "d1-07",
      isAutoregulated: true,
      baseSets: { basic: 2, metabolite: 2, resensitization: 1 },
    },
    {
      slotId: "d4-01",
      muscleCategory: "Glutes",
      dayNumber: 4,
      order: 1,
      pairedSlotId: "d2-01",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d4-02",
      muscleCategory: "Hamstring Hip Hinge",
      dayNumber: 4,
      order: 2,
      pairedSlotId: "d2-03",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d4-03",
      muscleCategory: "Quads",
      dayNumber: 4,
      order: 3,
      pairedSlotId: "d2-01",
      isAutoregulated: false,
      baseSets: { basic: 3, metabolite: 4, resensitization: 3 },
    },
    {
      slotId: "d4-04",
      muscleCategory: "Biceps",
      dayNumber: 4,
      order: 4,
      pairedSlotId: "d1-05",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d4-05",
      muscleCategory: "Traps",
      dayNumber: 4,
      order: 5,
      pairedSlotId: "d1-06",
      isAutoregulated: true,
      baseSets: { basic: 3, metabolite: 3, resensitization: 2 },
    },
    {
      slotId: "d4-06",
      muscleCategory: "Calves",
      dayNumber: 4,
      order: 6,
      pairedSlotId: "d2-04",
      isAutoregulated: false,
      baseSets: { basic: 6, metabolite: 6, resensitization: 5 },
    },
  ],
  exerciseCategories: {},
};
