import type { RpTemplate } from "./rp-types";

export const RP_TEMPLATE_NC4: RpTemplate = {
  id: "nc4",
  name: "Chest & Back (4 Days)",
  daysPerWeek: 4,
  dayTitles: ["Chest Push", "Back Pull", "Chest Push", "Back Pull"],
  restDayPattern: [0, 1, 0, 1],
  exerciseCategories: {},
  slots: [
    {
      slotId: "d1-01",
      muscleCategory: "Incline Push",
      dayNumber: 1,
      order: 1,
      pairedSlotId: "d3-03",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d1-02",
      muscleCategory: "Chest Isolation",
      dayNumber: 1,
      order: 2,
      pairedSlotId: "d3-02",
      supersetWith: "d1-e01",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d1-03",
      muscleCategory: "Horizontal Push",
      dayNumber: 1,
      order: 3,
      pairedSlotId: "d3-01",
      isAutoregulated: true,
      baseSets: {
        basic: 2,
        metabolite: 2,
        resensitization: 1,
      },
    },
    {
      slotId: "d1-04",
      muscleCategory: "Vertical Triceps",
      dayNumber: 1,
      order: 4,
      pairedSlotId: "d3-04",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d1-05",
      muscleCategory: "Side Delts",
      dayNumber: 1,
      order: 5,
      pairedSlotId: "d2-04",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d1-06",
      muscleCategory: "Quads",
      dayNumber: 1,
      order: 6,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d1-07",
      muscleCategory: "Calves",
      dayNumber: 1,
      order: 7,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 4,
        metabolite: 4,
        resensitization: 3,
      },
    },
    {
      slotId: "d1-e01",
      muscleCategory: "Horizontal Push",
      dayNumber: 1,
      order: 901,
      pairedSlotId: "d1-02",
      supersetWith: "d1-02",
      isAutoregulated: true,
      baseSets: {
        basic: 0,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d2-01",
      muscleCategory: "Vertical Pull",
      dayNumber: 2,
      order: 1,
      pairedSlotId: "d4-03",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d2-02",
      muscleCategory: "Vertical Pull",
      dayNumber: 2,
      order: 2,
      pairedSlotId: "d4-03",
      supersetWith: "d2-e01",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d2-03",
      muscleCategory: "Horizontal Pull",
      dayNumber: 2,
      order: 3,
      pairedSlotId: "d4-01",
      isAutoregulated: true,
      baseSets: {
        basic: 2,
        metabolite: 2,
        resensitization: 1,
      },
    },
    {
      slotId: "d2-04",
      muscleCategory: "Rear or Side Delts",
      dayNumber: 2,
      order: 4,
      pairedSlotId: "d4-04",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d2-05",
      muscleCategory: "Biceps",
      dayNumber: 2,
      order: 5,
      pairedSlotId: "d4-05",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d2-06",
      muscleCategory: "Abs",
      dayNumber: 2,
      order: 6,
      pairedSlotId: "d4-06",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d2-07",
      muscleCategory: "Hamstring Isolation",
      dayNumber: 2,
      order: 7,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 2,
        metabolite: 2,
        resensitization: 1,
      },
    },
    {
      slotId: "d2-e01",
      muscleCategory: "Vertical Pull",
      dayNumber: 2,
      order: 901,
      pairedSlotId: "d2-02",
      supersetWith: "d2-02",
      isAutoregulated: true,
      baseSets: {
        basic: 0,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d3-01",
      muscleCategory: "Horizontal Push",
      dayNumber: 3,
      order: 1,
      pairedSlotId: "d1-03",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d3-02",
      muscleCategory: "Chest Isolation",
      dayNumber: 3,
      order: 2,
      pairedSlotId: "d1-02",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d3-03",
      muscleCategory: "Incline Push",
      dayNumber: 3,
      order: 3,
      pairedSlotId: "d1-01",
      isAutoregulated: true,
      baseSets: {
        basic: 2,
        metabolite: 2,
        resensitization: 1,
      },
    },
    {
      slotId: "d3-04",
      muscleCategory: "Horizontal Triceps",
      dayNumber: 3,
      order: 4,
      pairedSlotId: "d1-04",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d3-05",
      muscleCategory: "Glutes",
      dayNumber: 3,
      order: 5,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d3-06",
      muscleCategory: "Quads",
      dayNumber: 3,
      order: 6,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d3-07",
      muscleCategory: "Calves",
      dayNumber: 3,
      order: 7,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 4,
        metabolite: 4,
        resensitization: 3,
      },
    },
    {
      slotId: "d4-01",
      muscleCategory: "Horizontal Pull",
      dayNumber: 4,
      order: 1,
      pairedSlotId: "d2-03",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d4-02",
      muscleCategory: "Horizontal Pull",
      dayNumber: 4,
      order: 2,
      pairedSlotId: "d2-03",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 0,
      },
    },
    {
      slotId: "d4-03",
      muscleCategory: "Vertical Pull",
      dayNumber: 4,
      order: 3,
      pairedSlotId: "d2-01",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 4,
        resensitization: 3,
      },
    },
    {
      slotId: "d4-04",
      muscleCategory: "Rear Delts",
      dayNumber: 4,
      order: 4,
      pairedSlotId: "d2-04",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d4-05",
      muscleCategory: "Biceps",
      dayNumber: 4,
      order: 5,
      pairedSlotId: "d2-05",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d4-06",
      muscleCategory: "Abs",
      dayNumber: 4,
      order: 6,
      pairedSlotId: "d2-06",
      isAutoregulated: true,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    },
    {
      slotId: "d4-07",
      muscleCategory: "Hamstring Hip Hinge",
      dayNumber: 4,
      order: 7,
      pairedSlotId: null,
      isAutoregulated: false,
      baseSets: {
        basic: 3,
        metabolite: 3,
        resensitization: 2,
      },
    }
  ],
};
